"""
GeneratedAsset model per design.md §5.

Represents assets generated by pipelines, such as thumbnails,
preview images, and other derived content.
"""

from datetime import datetime, timezone
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from app.models.enums import AssetType, Visibility


class GeneratedAsset(BaseModel):
    """
    Generated asset document stored in Cosmos DB.
    
    Partition Key: content_id
    Container: generated_assets
    
    Per design.md §5 GeneratedAsset schema.
    """
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, description="Unique asset ID")
    
    # Relations
    content_id: UUID = Field(description="Related content ID (partition key)")
    run_id: UUID = Field(description="Pipeline run that created this asset")
    
    # Asset identification
    asset_type: AssetType = Field(description="Type: thumbnail, preview, og_image")
    
    # Storage
    storage_url: str = Field(description="Azure Blob Storage URL")
    cdn_url: Optional[str] = Field(
        default=None,
        description="CDN URL for public assets"
    )
    
    # Generation metadata
    is_generated: bool = Field(
        default=True,
        description="Always true for generated assets"
    )
    model_used: str = Field(
        description="Model used for generation: gpt-4o, dall-e-3, etc."
    )
    visibility: Visibility = Field(
        default=Visibility.INTERNAL,
        description="Asset visibility: public or internal"
    )
    
    # Image dimensions (for image assets)
    width: Optional[int] = Field(default=None, description="Image width in pixels")
    height: Optional[int] = Field(default=None, description="Image height in pixels")
    format: Optional[str] = Field(
        default=None,
        description="File format: png, jpg, webp"
    )
    size_bytes: Optional[int] = Field(
        default=None,
        description="File size in bytes"
    )
    
    # Versioning
    enrichment_version: str = Field(
        description="Enrichment version this asset was generated with"
    )
    
    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the asset was created"
    )
    
    def to_cosmos_document(self) -> dict[str, Any]:
        """Convert to Cosmos DB document format."""
        doc = self.model_dump(mode="json")
        doc["id"] = str(self.id)
        doc["content_id"] = str(self.content_id)
        doc["run_id"] = str(self.run_id)
        return doc
    
    @classmethod
    def from_cosmos_document(cls, doc: dict[str, Any]) -> "GeneratedAsset":
        """Create from Cosmos DB document."""
        return cls.model_validate(doc)
    
    class Config:
        use_enum_values = True
